CREATE TABLE IF NOT EXISTS schema_migrations(version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS trips(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,origin varchar(3) NOT NULL,destination varchar(3) NOT NULL,start_date date NOT NULL,end_date date NOT NULL,pax_count integer NOT NULL CHECK(pax_count>0),theme varchar(50),budget_limit_minor bigint NOT NULL CHECK(budget_limit_minor>0),currency char(3) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS bookings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),trip_id uuid NOT NULL REFERENCES trips(id),proposal_id text NOT NULL,quote_id text NOT NULL,quote_version text NOT NULL,quote_expires_at timestamptz NOT NULL,pricing_source text NOT NULL,booking_status text NOT NULL,payment_status text NOT NULL,refund_status text NOT NULL DEFAULT 'NONE',total_amount_minor bigint NOT NULL CHECK(total_amount_minor>=0),currency char(3) NOT NULL,idempotency_key text NOT NULL UNIQUE,request_fingerprint text,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS booking_components(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,type text NOT NULL CHECK(type IN('FLIGHT','HOTEL')),supplier_id text NOT NULL,supplier_quote_key text NOT NULL,supplier_hold_id text,supplier_reference text,net_cost_minor bigint NOT NULL,currency char(3) NOT NULL,status text NOT NULL,compensation_status text NOT NULL DEFAULT 'NONE',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS supplier_operations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,component_id uuid NOT NULL REFERENCES booking_components(id) ON DELETE CASCADE,operation_type text NOT NULL,operation_key text NOT NULL UNIQUE,supplier_id text NOT NULL,attempt integer NOT NULL DEFAULT 0,status text NOT NULL,next_retry_at timestamptz, supplier_reference text,last_error text,started_at timestamptz,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,gateway_reference text,provider text NOT NULL,payment_status text NOT NULL,amount_minor bigint NOT NULL,currency char(3) NOT NULL,refunded_amount_minor bigint NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payment_operations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,operation_key text NOT NULL UNIQUE,operation_type text NOT NULL,status text NOT NULL,attempt integer NOT NULL DEFAULT 0,gateway_reference text,last_error text,next_retry_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS refunds(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,operation_key text NOT NULL UNIQUE,status text NOT NULL,amount_minor bigint NOT NULL,provider_reference text,last_error text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS idempotency_records(idempotency_key text PRIMARY KEY,request_hash text NOT NULL,response_payload jsonb,status_code integer,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS outbox_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),aggregate_type text NOT NULL,aggregate_id uuid NOT NULL,event_type text NOT NULL,payload jsonb NOT NULL,status text NOT NULL DEFAULT 'PENDING',attempt integer NOT NULL DEFAULT 0,next_attempt_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),processing_at timestamptz,processed_at timestamptz);
CREATE TABLE IF NOT EXISTS audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),booking_id uuid REFERENCES bookings(id),actor_type text NOT NULL,actor_id text NOT NULL,initiated_by text,authorized_by text,executed_by text NOT NULL,action text NOT NULL,previous_state text,new_state text,request_id text,trace_id text,idempotency_key text,reason text,metadata jsonb,timestamp timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sse_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),stream_id uuid NOT NULL,booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,stream_seq bigint NOT NULL,event_type text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(stream_id,stream_seq));
CREATE INDEX IF NOT EXISTS idx_outbox_pending ON outbox_events(status,next_attempt_at,created_at); CREATE INDEX IF NOT EXISTS idx_supplier_verify ON supplier_operations(status,next_retry_at); CREATE INDEX IF NOT EXISTS idx_sse_stream ON sse_events(stream_id,stream_seq); CREATE INDEX IF NOT EXISTS idx_booking_status ON bookings(booking_status); CREATE INDEX IF NOT EXISTS idx_component_booking ON booking_components(booking_id); CREATE INDEX IF NOT EXISTS idx_payment_booking ON payments(booking_id); CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_gateway ON payments(booking_id,gateway_reference) WHERE gateway_reference IS NOT NULL;

CREATE TABLE IF NOT EXISTS payment_webhook_events(event_id text PRIMARY KEY, booking_id uuid NOT NULL REFERENCES bookings(id), gateway_reference text NOT NULL, received_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE outbox_events ADD COLUMN IF NOT EXISTS processing_at timestamptz;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS request_fingerprint text;
INSERT INTO schema_migrations(version) VALUES('0001_initial_schema') ON CONFLICT(version) DO UPDATE SET applied_at=now();
