"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OperationStatus = exports.CompensationStatus = exports.ComponentStatus = exports.RefundStatus = exports.PaymentStatus = exports.BookingStatus = void 0;
var BookingStatus;
(function (BookingStatus) {
    BookingStatus["INITIALIZED"] = "INITIALIZED";
    BookingStatus["VERIFYING"] = "VERIFYING";
    BookingStatus["PRICE_CONFIRMED"] = "PRICE_CONFIRMED";
    BookingStatus["INVENTORY_LOCK_REQUESTED"] = "INVENTORY_LOCK_REQUESTED";
    BookingStatus["INVENTORY_HELD"] = "INVENTORY_HELD";
    BookingStatus["HOLD_FAILED"] = "HOLD_FAILED";
    BookingStatus["HOLD_EXPIRED"] = "HOLD_EXPIRED";
    BookingStatus["PAYMENT_PENDING"] = "PAYMENT_PENDING";
    BookingStatus["PAYMENT_REQUIRES_ACTION"] = "PAYMENT_REQUIRES_ACTION";
    BookingStatus["PAYMENT_AUTHORIZED"] = "PAYMENT_AUTHORIZED";
    BookingStatus["PAYMENT_CAPTURED"] = "PAYMENT_CAPTURED";
    BookingStatus["BOOKING_PROCESSING"] = "BOOKING_PROCESSING";
    BookingStatus["SUPPLIER_PENDING"] = "SUPPLIER_PENDING";
    BookingStatus["CONFIRMED"] = "CONFIRMED";
    BookingStatus["BOOKING_FAILED"] = "BOOKING_FAILED";
    BookingStatus["COMPENSATION_PENDING"] = "COMPENSATION_PENDING";
    BookingStatus["COMPENSATION_PARTIAL"] = "COMPENSATION_PARTIAL";
    BookingStatus["COMPENSATION_FAILED"] = "COMPENSATION_FAILED";
    BookingStatus["REFUND_PENDING"] = "REFUND_PENDING";
    BookingStatus["REFUNDED"] = "REFUNDED";
    BookingStatus["REFUND_FAILED"] = "REFUND_FAILED";
    BookingStatus["ESCALATED_HITL"] = "ESCALATED_HITL";
})(BookingStatus || (exports.BookingStatus = BookingStatus = {}));
var PaymentStatus;
(function (PaymentStatus) {
    PaymentStatus["INITIATED"] = "INITIATED";
    PaymentStatus["REQUIRES_ACTION"] = "REQUIRES_ACTION";
    PaymentStatus["AUTHORIZED"] = "AUTHORIZED";
    PaymentStatus["CAPTURED"] = "CAPTURED";
    PaymentStatus["FAILED"] = "FAILED";
    PaymentStatus["REFUND_PENDING"] = "REFUND_PENDING";
    PaymentStatus["REFUNDED"] = "REFUNDED";
    PaymentStatus["REFUND_FAILED"] = "REFUND_FAILED";
})(PaymentStatus || (exports.PaymentStatus = PaymentStatus = {}));
var RefundStatus;
(function (RefundStatus) {
    RefundStatus["NONE"] = "NONE";
    RefundStatus["PENDING"] = "PENDING";
    RefundStatus["REFUNDED"] = "REFUNDED";
    RefundStatus["FAILED"] = "FAILED";
})(RefundStatus || (exports.RefundStatus = RefundStatus = {}));
var ComponentStatus;
(function (ComponentStatus) {
    ComponentStatus["PENDING"] = "PENDING";
    ComponentStatus["HOLD_REQUESTED"] = "HOLD_REQUESTED";
    ComponentStatus["HELD"] = "HELD";
    ComponentStatus["HOLD_FAILED"] = "HOLD_FAILED";
    ComponentStatus["HOLD_UNKNOWN"] = "HOLD_UNKNOWN";
    ComponentStatus["COMMIT_REQUESTED"] = "COMMIT_REQUESTED";
    ComponentStatus["COMMITTED"] = "COMMITTED";
    ComponentStatus["COMMIT_UNKNOWN"] = "COMMIT_UNKNOWN";
    ComponentStatus["NOT_COMMITTED"] = "NOT_COMMITTED";
    ComponentStatus["FAILED"] = "FAILED";
    ComponentStatus["CANCEL_REQUESTED"] = "CANCEL_REQUESTED";
    ComponentStatus["CANCELLED"] = "CANCELLED";
    ComponentStatus["CANCEL_UNKNOWN"] = "CANCEL_UNKNOWN";
    ComponentStatus["CANCEL_FAILED"] = "CANCEL_FAILED";
})(ComponentStatus || (exports.ComponentStatus = ComponentStatus = {}));
var CompensationStatus;
(function (CompensationStatus) {
    CompensationStatus["NONE"] = "NONE";
    CompensationStatus["PENDING"] = "PENDING";
    CompensationStatus["PARTIAL"] = "PARTIAL";
    CompensationStatus["COMPLETED"] = "COMPLETED";
    CompensationStatus["FAILED"] = "FAILED";
})(CompensationStatus || (exports.CompensationStatus = CompensationStatus = {}));
var OperationStatus;
(function (OperationStatus) {
    OperationStatus["REQUESTED"] = "REQUESTED";
    OperationStatus["RUNNING"] = "RUNNING";
    OperationStatus["SUCCEEDED"] = "SUCCEEDED";
    OperationStatus["FAILED"] = "FAILED";
    OperationStatus["UNKNOWN"] = "UNKNOWN";
    OperationStatus["VERIFY_REQUESTED"] = "VERIFY_REQUESTED";
    OperationStatus["EXHAUSTED"] = "EXHAUSTED";
})(OperationStatus || (exports.OperationStatus = OperationStatus = {}));
